# -*- coding: utf-8 -*-
"""CalculadoraIP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_k2rR_KaezpjUVop3aTSyO3l4b8G7P-d
"""

# Entrada de dados por parte do usuário
ip = input(str("Coloque o IP: "))
mascara = input(str("Coloque a mascara que deseja aplicar no ip: "))
numero_func = input(str("Selecione a primeira ou a segunda função: "))

# Caso o usuário coloque um IP inválido

# Abaixo temos a trecho que separa o ip e ao mesmo tempo o
# Modulo de correção de dados
mascara = mascara.replace("/", "")
ip_dividido = ip.split(".")

for i in ip_dividido:
  if int(i) > 256 and int(i) < 0 and len(ip_dividido) != 4:
    print("")
    print("Por favor insira um ip válido")
    ip = input(str("Coloque o IP: "))

if int(mascara) < 25 or int(mascara) > 32:
  print("")
  print("Essa mascara não existe, tente uma mascara dentro de /25 a /32")
  mascara = input(str("Coloque a mascara que deseja aplicar no ip: "))
elif numero_func != "1" or numero_func != "2":
  print("")
  print("Essa função não existe, " +
  "para primeira função digite 1, " +
  "para segunda função digite 2")
  numero_func = input(str("Selecione a primeira ou a segunda função: ")) 

principal = ip_dividido[0] + "." +  ip_dividido[1] +  "." + ip_dividido[2] + "."
last = int(ip_dividido[3])


# Declaração de variáveis 
host = 0
primeiro_ip = host + 1
divisor_total = 2 ** (int(mascara) - 24)
broadcast = int(256 / divisor_total) - 1
ultimo_ip = int(broadcast) - 1


# Primeira função que traz a tabela contendo todas as subredes
def primeira_func(ip, mascara, host, primeiro_ip, ultimo_ip, broadcast):
  print("")
  print("   Host    | Primeira IP disponivel " +
        "| Último IP disponivel | Broadcast")
  for i in range(divisor_total):
      print(principal + str(host) + " |" + "     " 
            + principal + str(primeiro_ip) + "     |"
            + "     " + principal + str(ultimo_ip) + "     |"
            + "     " + principal + str(broadcast))
      host = host + int(256 / divisor_total)
      primeiro_ip = host + 1
      broadcast = host + int(256 / divisor_total) - 1
      ultimo_ip = broadcast - 1

# Segunda função que busca a subrede especifica onde o ip está
def segunda_func(ip, mascara, host, primeiro_ip, ultimo_ip, broadcast):
  print("")
  print("   Host    | Primeira IP disponivel " +
        "| Último IP disponivel | Broadcast")
  for i in range(divisor_total):
    if host <= last and broadcast >= last:
      print(principal + str(host) + " |"
        + "     " + principal + str(primeiro_ip) + "     |"
        + "     " + principal + str(ultimo_ip) + "     |"
        + "     " + principal + str(broadcast))
      host = host + int(256 / divisor_total)
      broadcast = host + int(256 / divisor_total) - 1
    else:
      host = host + int(256 / divisor_total)
      primeiro_ip = host + 1
      broadcast = host + int(256 / divisor_total) - 1
      ultimo_ip = broadcast - 1

# Bloco de decisão que diferencia a primeira da segunda função

if numero_func == "1":
  primeira_func(ip, mascara, host, primeiro_ip, ultimo_ip, broadcast)
elif numero_func == "2" :
  segunda_func(ip, mascara, host, primeiro_ip, ultimo_ip, broadcast)